### ISSUE TITLE
POI Information & General Styling

### ISSUE THREAD

**Issue by greenitthe** [Moser2010/d-dMap#1]
Your various points of interest have Religions & Gods or Amenities, for example, which are listed out but missing spaces between each item in the list.

Like the Idea. Ill think on this ---- 
Stylistically I prefer a modal pop-up with this information, as I find crowding it at the bottom to be too much of a squish, but that is falling more under personal preference than a programmatic issue.

Additionally, since your map suffers from the typical Leaflet issue where markers scale out to ridiculous size when you zoom out, the map can be a bit crowded. It would be nice to have toggles to select all and deselect all layers.

Complete ---- 
Finally, from your main menu, under DM-T, mousing over the PFD Reference Document doesn't highlight it properly.

**Comment by Moser2010** [comment]
I made a few changes to help the site look and feel a little better on both desktop and on mobile. It should look a little different now. I am not sure if I am going to do the modal pop-up but the idea was one that I toyed with before I began development of the site and while I like it on the desktop and think it would be good for functionality I found that I wasn't a huge fan of the idea on mobile. 

I think down the road I will end up moving it over to the modal format though as I do like the idea.
